server:
  port: 1992

spring:
  application:
    name: Book-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
#            zkNodes: localhost:2181,localhost:2182,localhost:2183

      function:
          definition: newBook;

      bindings:
        newBook-in-0:
          destination: spring-cloud-stream
